### ISSUE TITLE
app-features does not compile with 6.12.0

### ISSUE THREAD

**Issue by jsi** [enonic/app-features#44]
We need to upgrade some of the code in this app to work with Enonic XP 6.12:

Try setting xpVersion in gradle.properties to 6.12.0.  This does not compile:

> Task :compileTestJava
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ContentPageJsTest.java:3: error: package com.enonic.xp.testing.script does not exist
import com.enonic.xp.testing.script.ScriptRunnerSupport;
                                   ^
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ContentPageJsTest.java:6: error: cannot find symbol
    extends ScriptRunnerSupport
            ^
  symbol: class ScriptRunnerSupport
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ErrorJsTest.java:3: error: package com.enonic.xp.testing.script does not exist
import com.enonic.xp.testing.script.ScriptRunnerSupport;
                                   ^
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ErrorJsTest.java:6: error: cannot find symbol
    extends ScriptRunnerSupport
            ^
  symbol: class ScriptRunnerSupport
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ContentPageJsTest.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jsi/Documents/EnonicGIT/xp/apps/app-features/src/test/java/com/enonic/app/features/ErrorJsTest.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
6 errors
